version: 0.2

env:
  shell: bash

phases:
  install:
    runtime-versions:
       python: 3.8
    commands: 
      - echo set python runtime version 3.8
      - pip install pygame
      - pip install simple-pid

  pre_build:
    commands:
      - echo compile
      - cp -R ./src /home/carla/graic-workspace/src
      # - cd /home/carla/graic-workspace/
      # - source /opt/ros/noetic/setup.bash
      - cd /home/carla/carla-simulator/CarlaUE4/Content/
      - wget https://github.com/PoPGRI/Race/releases/download/0.1.0/map_package_0.1.0.zip 
      - cd /home/carla/carla-simulator/
      - echo "SDL_VIDEODRIVER=offscreen ./CarlaUE4.sh -opengl" > runCarla.sh
      - chmod +x runCarla.sh
      - nohup ./runCarla.sh & echo $! > pidfile
      - cd /home/carla
      # - source .bashrc
      - cat .bashrc
      - cd /home/carla/graic-workspace/
      - source /opt/ros/noetic/setup.bash
      - catkin_make
      # - source /home/carla/carla-ros-bridge/catkin_ws/devel/setup.bash
      - export PYTHONPATH=$PYTHONPATH:/home/carla/carla-simulator/PythonAPI/carla/dist/carla-0.9.11-py3.7-linux-x86_64.egg
      - source /home/carla/carla-ros-bridge/catkin_ws/devel/setup.bash
      - source devel/setup.bash --extend

    
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - nohup roslaunch race carla_single.launch & echo $! > pidfile
      - sleep 120 && echo "time to shutdown"
      - pkill ros
      - pkill Carla
      - cat /home/carla/graic-workspace/src/race_util_module/evaluation_node


