version: 0.2

phases:
  install:
    runtime-versions:
       python: 3.8
    commands: 
      - echo set python runtime version 3.8

  pre_build:
    commands:
      - echo compile
      # - cd /
      # - ls
      # - cd /home 
      # - ls
      # - cd /opt
      - . /opt/ros/noetic/setup.bash
      - catkin_make
      
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`


